---
title: "R Notebook"
output: html_notebook
---
We received a separate file on academic scores from NIE. This file describes the data handling for academic scores before main analyses. 

```{r required packages}
pkgs = c("tidyverse", "readxl", "writexl", "naniar", "mice", "missMethods")
inst = lapply(pkgs, library, character.only=TRUE)
set.seed(555)
```

```{r Define file path}
root_dir <-'filepath'
```

```{Preliminary data wrangling}
data_academics <- read_xlsx(file.path(root_dir,'academics_raw.xlsx')) %>% 
  mutate(studId = as.factor(studId))

data_selected_datasets <- readRDS(file.path(root_dir,'studId_dataset_mapping.rds'))

df_explore <- data_academics %>% inner_join(data_selected_datasets, by = "studId") %>% 
  rename(pre_tgaia = assignment1_NOAI,
         post_tgaia = assignment2_AI) %>% 
  mutate(pre_tgaia = as.numeric(pre_tgaia),
         post_tgaia = as.numeric(post_tgaia))
```

```{r How much data are we missing?}
# raw count of missing
sapply(df_explore, function(x) sum(is.na(x)))

# proportion of missing
sapply(df_explore, function(x) mean(is.na(x)) * 100)
```


```{r Impute missing data}
data_for_imputation <- df_explore[, c("pre_tgaia", "post_tgaia")]
# impute_em offers two types:
  # stochastic = FALSE: Fills with the exact expected value (reduces variance, not recommended)
  # stochastic = TRUE: Adds random noise based on the error distribution (better for preserving variance)
imputed_data_em <- impute_EM(data_for_imputation, stochastic = TRUE)
df_explore_imputed <- cbind(df_explore[, "studId"], imputed_data_em)

saveRDS(df_explore_imputed, file = file.path(root_dir,'/replication_academics.xlsx'))
```

